#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
#ifndef KEYBOARDSDK_SWIFT_H
#define KEYBOARDSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#import <KeyboardSDK/KeyboardSDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="KeyboardSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)


@class NSCoder;
@class UILongPressGestureRecognizer;

IB_DESIGNABLE
SWIFT_CLASS("_TtC11KeyboardSDK13DHColorPicker")
@interface DHColorPicker : UIView
@property (nonatomic) IBInspectable CGFloat elementSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
+ (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)drawRect:(CGRect)rect;
- (void)touchedColorWithGestureRecognizer:(UILongPressGestureRecognizer * _Nonnull)gestureRecognizer;
@end


SWIFT_CLASS("_TtC11KeyboardSDK15ENClipboardCell")
@interface ENClipboardCell : UICollectionViewCell
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11KeyboardSDK15ENClipboardView")
@interface ENClipboardView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)bottomKeyboardHandler;
- (void)btnClipboardSelectHandler;
- (void)btnCancelHandler;
- (void)btnClipboardDeleteHandler;
@end

@class UICollectionView;
@class NSIndexPath;

@interface ENClipboardView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface ENClipboardView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDelegate>
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UICollectionViewLayout;

@interface ENClipboardView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11KeyboardSDK25ENCollectionViewPresenter")
@interface ENCollectionViewPresenter : NSObject
- (void)updateCellDataFor:(UICollectionViewCell * _Nullable)cell indexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)loadData;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIScrollView;

@interface ENCollectionViewPresenter (SWIFT_EXTENSION(KeyboardSDK)) <UIScrollViewDelegate>
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end

@class NSString;
@class UICollectionReusableView;

@interface ENCollectionViewPresenter (SWIFT_EXTENSION(KeyboardSDK))
- (NSInteger)numberOfItemsWithSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)dequeueCellFor:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)sizeForItemAt:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)reloadItemsWithCollection:(UICollectionView * _Nullable)collection new:(NSIndexPath * _Nonnull)new_ old:(NSIndexPath * _Nullable)old;
- (UIEdgeInsets)insetForSectionAtSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)sizeForHeaderWithSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)sizeForFooterWithSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionReusableView * _Nonnull)dequeueViewForSupplementaryElementOfKind:(NSString * _Nonnull)kind at:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)didSelectedItemAt:(NSIndexPath * _Nonnull)indexPath;
- (void)didDeSelectedItemAt:(NSIndexPath * _Nonnull)indexPath;
@end


@interface ENCollectionViewPresenter (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionReusableView * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView viewForSupplementaryElementOfKind:(NSString * _Nonnull)kind atIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout referenceSizeForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout referenceSizeForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC11KeyboardSDK13ENContentView")
@interface ENContentView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)bottomKeyboardHandler;
@end


@interface ENContentView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface ENContentView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDelegate>
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface ENContentView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11KeyboardSDK17ENContentViewCell")
@interface ENContentViewCell : UICollectionViewCell
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class UIButton;
@class NSLayoutConstraint;
@class NSBundle;

SWIFT_CLASS("_TtC11KeyboardSDK21ENGuideViewController")
@interface ENGuideViewController : UIViewController <UIScrollViewDelegate>
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnBack;
@property (nonatomic, weak) IBOutlet UIScrollView * _Null_unspecified guideScrollView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewGuideFirst;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified constraintGuideFirstWidth;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewGuildeSecond;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified constraintGuideSecondWidth;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewGuideThird;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified constraintGuideThirdWidth;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnConfirm;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)btnConfirmHandler;
- (void)btnCloseHandler;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ENGuideViewController (SWIFT_EXTENSION(KeyboardSDK))
/// 스크롤 이벤트가 끝났을 때
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end


/// UIInputViewController 상속.  Client에서 해당 클래스를 상속받아 Keyboard Extension을 구현할 수 있도록 한다.
SWIFT_CLASS("_TtC11KeyboardSDK21ENInputViewController")
@interface ENInputViewController : UIInputViewController
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// 커스텀 영역
/// <ul>
///   <li>
///     키보드 위 툴바 부분을 세팅함.
///   </li>
///   <li>
///     여기에 사용 되는 기본적인 뷰는 wrapper 인 UIView
///   </li>
///   <li>
///     그 안에 기본적으로 사용되는 툴바인 ScrollView
///   </li>
///   <li>
///     광고나,, 붙여넣기 뷰는 Constraint 로 보여줬다 가렸다가 함.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC11KeyboardSDK24ENKeyboardCustomAreaView")
@interface ENKeyboardCustomAreaView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/// 툴바 버튼 바깥 영역 터치 핸들러
- (void)buttonTouchUpOutSide:(UIButton * _Nonnull)sender;
/// 툴바 터치 다운 핸들러
- (void)buttonTouchDown:(UIButton * _Nonnull)sender;
/// 툴바 터치 업 핸들러
- (void)buttonTouchUpInSide:(UIButton * _Nonnull)sender;
@end

@class WKUserContentController;
@class WKScriptMessage;

SWIFT_CLASS("_TtC11KeyboardSDK31ENKeyboardInquiryViewController")
@interface ENKeyboardInquiryViewController : UIViewController <UIScrollViewDelegate, WKNavigationDelegate, WKScriptMessageHandler, WKUIDelegate>
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewWebViewFrame;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewWillLayoutSubviews;
- (void)viewDidLayoutSubviews;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (IBAction)btnCloseHandler:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WKWebView;
@class WKWebViewConfiguration;
@class WKNavigationAction;
@class WKWindowFeatures;
@class WKNavigation;
@class WKFrameInfo;

@interface ENKeyboardInquiryViewController (SWIFT_EXTENSION(KeyboardSDK))
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
@end


SWIFT_CLASS("_TtC11KeyboardSDK18ENKeyboardMoreView")
@interface ENKeyboardMoreView : UIView <UIGestureRecognizerDelegate, UIScrollViewDelegate, WKNavigationDelegate, WKUIDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)btnCloseHandler:(UIButton * _Nonnull)sender;
- (void)layoutSubviews;
@end


@interface ENKeyboardMoreView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDelegate>
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface ENKeyboardMoreView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface ENKeyboardMoreView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end

@class UIGestureRecognizer;

@interface ENKeyboardMoreView (SWIFT_EXTENSION(KeyboardSDK))
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end

@class UIImageView;
@class UITapGestureRecognizer;

SWIFT_CLASS("_TtC11KeyboardSDK29ENKeyboardSoundViewController")
@interface ENKeyboardSoundViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewOpacity;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewContent;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewDefaultSound;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgDefaultSoundCheck;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewSecondSound;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgSecondSoundCheck;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewThirdSound;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgThirdSoundCheck;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewFourSound;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgFourSoundCheck;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (IBAction)btnConfirmHandler:(UIButton * _Nonnull)sender;
- (IBAction)btnCancelHandler:(UIButton * _Nonnull)sender;
- (void)tapHandler:(UITapGestureRecognizer * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UILabel;

SWIFT_CLASS("_TtC11KeyboardSDK28ENKeyboardTypeViewController")
@interface ENKeyboardTypeViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewHeader;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewSelect;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewQwerty;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgQwerty;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblQwerty;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgQwertyCheck;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewTenKey;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgTenKey;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblTenKey;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgTenKeyCheck;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewSample;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified constraintHeightViewSample;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (IBAction)btnBackHandler:(UIButton * _Nonnull)sender;
- (void)viewSelectGestureHandler:(UITapGestureRecognizer * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class UISlider;
@class UISwitch;

SWIFT_CLASS("_TtC11KeyboardSDK20ENMainViewController")
@interface ENMainViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewHeader;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewKeyboardType;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblKeyboardType;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewKeyboardTheme;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewKeyboardHeight;
@property (nonatomic, weak) IBOutlet UISlider * _Null_unspecified sliderHeight;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewKeyboardSound;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblKeyboardSound;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewKeyboardVibrator;
@property (nonatomic, weak) IBOutlet UISwitch * _Null_unspecified switchKeyboardVibrator;
@property (nonatomic, weak) IBOutlet UISlider * _Null_unspecified sliderKeyboardVibrator;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewPreview;
@property (nonatomic, weak) IBOutlet UISwitch * _Null_unspecified switchPreview;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewKeyboardSetting;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewSample;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified constraintHeightViewSample;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (IBAction)btnBackHandler:(id _Nonnull)sender;
- (IBAction)sliderChangeHandler:(UISlider * _Nonnull)sender;
- (IBAction)switchKeyboardVibratorHandler:(UISwitch * _Nonnull)sender;
- (IBAction)sliderKeyboardVibaratorHandler:(UISlider * _Nonnull)sender;
- (IBAction)switchPreviewChangeHandler:(UISwitch * _Nonnull)sender;
- (void)viewMoveGesture:(UITapGestureRecognizer * _Nonnull)sender;
- (void)otherViewTap;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS("_TtC11KeyboardSDK14ENMoreViewCell")
@interface ENMoreViewCell : UICollectionViewCell
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11KeyboardSDK31ENNewThemeManagerViewController")
@interface ENNewThemeManagerViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified displayTitleLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified keyboardSampleView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified keyboardSampleViewHeight;
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified collectionView;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ENNewThemeManagerViewController (SWIFT_EXTENSION(KeyboardSDK))
- (IBAction)backButtonClicked:(id _Nonnull)sender;
/// 선택된 테마 미리보기 뷰의 적용버튼 동작
/// \param sender 버튼
///
- (IBAction)confirmThemeButtonClicked:(id _Nonnull)sender;
/// 선택된 테마 미리보기 뷰의 취소 버튼 동작
/// \param sender 버튼
///
- (IBAction)cancelThemeButtonClicked:(id _Nonnull)sender;
@end





/// 최 상단 공지 뷰
/// <ul>
///   <li>
///     이 부분은 툴바 상단 부분에 보여지는 뷰
///   </li>
/// </ul>
SWIFT_CLASS("_TtC11KeyboardSDK12ENNotifyView")
@interface ENNotifyView : UIView <UIGestureRecognizerDelegate, UIScrollViewDelegate, WKNavigationDelegate, WKUIDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)updateNewsTitle;
- (void)btnNewshandler:(UIButton * _Nonnull)sender;
- (void)layoutSubviews;
- (void)btnCloseHandler:(UIButton * _Nonnull)sender;
@end


@interface ENNotifyView (SWIFT_EXTENSION(KeyboardSDK))
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11KeyboardSDK22ENPPZWebViewController")
@interface ENPPZWebViewController : UIViewController <UIScrollViewDelegate, WKNavigationDelegate, WKUIDelegate>
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewFrame;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified constraintBridgeHeight;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified tempView;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (IBAction)btnBridgeHeaderBack:(id _Nonnull)sender;
- (IBAction)btnBridgeHeaderClose:(id _Nonnull)sender;
- (IBAction)btnMainClose:(id _Nonnull)sender;
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webViewWebContentProcessDidTerminate:(WKWebView * _Nonnull)webView;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class ENTapGesture;

SWIFT_CLASS("_TtC11KeyboardSDK18ENPointContentView")
@interface ENPointContentView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)bottomKeyboardHandler;
- (void)tapHandller:(ENTapGesture * _Nonnull)sender;
@end


SWIFT_CLASS("_TtC11KeyboardSDK15ENTabButtonView")
@interface ENTabButtonView : UIView
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified displayLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified iconImageView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11KeyboardSDK21ENTabContentPresenter")
@interface ENTabContentPresenter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum ENThemeSelectedTab : NSInteger;

SWIFT_CLASS("_TtC11KeyboardSDK14ENTabPresenter")
@interface ENTabPresenter : NSObject
@property (nonatomic) enum ENThemeSelectedTab selectedTab;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ENTabPresenter (SWIFT_EXTENSION(KeyboardSDK))
- (void)tapGestureExcuteWithTap:(UITapGestureRecognizer * _Nonnull)tap;
@end


SWIFT_CLASS("_TtC11KeyboardSDK12ENTapGesture")
@interface ENTapGesture : UITapGestureRecognizer
- (nonnull instancetype)initWithTarget:(id _Nullable)target action:(SEL _Nullable)action OBJC_DESIGNATED_INITIALIZER;
@end

@class DHPaddedLabel;

SWIFT_CLASS("_TtC11KeyboardSDK33ENThemeCategoryCollectionViewCell")
@interface ENThemeCategoryCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet DHPaddedLabel * _Null_unspecified labelName;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified selecteIndicatorView;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11KeyboardSDK25ENThemeCategoryHeaderView")
@interface ENThemeCategoryHeaderView : GSKStretchyHeaderView
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified textCategoryCollectionView;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified constraintTextCategoryTopMargin;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@interface ENThemeCategoryHeaderView (SWIFT_EXTENSION(KeyboardSDK)) <GSKStretchyHeaderViewStretchDelegate>
- (void)stretchyHeaderView:(GSKStretchyHeaderView * _Nonnull)headerView didChangeStretchFactor:(CGFloat)stretchFactor;
@end


@interface ENThemeCategoryHeaderView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC11KeyboardSDK24ENThemeCategoryPresenter")
@interface ENThemeCategoryPresenter : ENCollectionViewPresenter
- (void)updateCellDataFor:(UICollectionViewCell * _Nullable)cell indexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)loadData;
@end



@interface ENThemeCategoryPresenter (SWIFT_EXTENSION(KeyboardSDK))
- (NSInteger)numberOfItemsWithSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)sizeForHeaderWithSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)didSelectedItemAt:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC11KeyboardSDK25ENThemeCollectionViewCell")
@interface ENThemeCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified rootView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified shadowView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified selectionView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageViewThumbnail;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageViewSelectIcon;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelName;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified badgeImageView;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ENThemeSelectedTab, closed) {
  ENThemeSelectedTabUnknown = 0,
  ENThemeSelectedTabCategory = 1001,
};


SWIFT_CLASS("_TtC11KeyboardSDK20ENThemeViewPresenter")
@interface ENThemeViewPresenter : ENTabContentPresenter
@end










@class NSURL;

@interface UIViewController (SWIFT_EXTENSION(KeyboardSDK))
- (BOOL)openURL:(NSURL * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11KeyboardSDK7URLUtil")
@interface URLUtil : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
#ifndef KEYBOARDSDK_SWIFT_H
#define KEYBOARDSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#import <KeyboardSDK/KeyboardSDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="KeyboardSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)


@class NSCoder;
@class UILongPressGestureRecognizer;

IB_DESIGNABLE
SWIFT_CLASS("_TtC11KeyboardSDK13DHColorPicker")
@interface DHColorPicker : UIView
@property (nonatomic) IBInspectable CGFloat elementSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
+ (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)drawRect:(CGRect)rect;
- (void)touchedColorWithGestureRecognizer:(UILongPressGestureRecognizer * _Nonnull)gestureRecognizer;
@end


SWIFT_CLASS("_TtC11KeyboardSDK15ENClipboardCell")
@interface ENClipboardCell : UICollectionViewCell
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11KeyboardSDK15ENClipboardView")
@interface ENClipboardView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)bottomKeyboardHandler;
- (void)btnClipboardSelectHandler;
- (void)btnCancelHandler;
- (void)btnClipboardDeleteHandler;
@end

@class UICollectionView;
@class NSIndexPath;

@interface ENClipboardView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface ENClipboardView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDelegate>
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UICollectionViewLayout;

@interface ENClipboardView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11KeyboardSDK25ENCollectionViewPresenter")
@interface ENCollectionViewPresenter : NSObject
- (void)updateCellDataFor:(UICollectionViewCell * _Nullable)cell indexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)loadData;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIScrollView;

@interface ENCollectionViewPresenter (SWIFT_EXTENSION(KeyboardSDK)) <UIScrollViewDelegate>
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end

@class NSString;
@class UICollectionReusableView;

@interface ENCollectionViewPresenter (SWIFT_EXTENSION(KeyboardSDK))
- (NSInteger)numberOfItemsWithSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)dequeueCellFor:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)sizeForItemAt:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)reloadItemsWithCollection:(UICollectionView * _Nullable)collection new:(NSIndexPath * _Nonnull)new_ old:(NSIndexPath * _Nullable)old;
- (UIEdgeInsets)insetForSectionAtSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)sizeForHeaderWithSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)sizeForFooterWithSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionReusableView * _Nonnull)dequeueViewForSupplementaryElementOfKind:(NSString * _Nonnull)kind at:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)didSelectedItemAt:(NSIndexPath * _Nonnull)indexPath;
- (void)didDeSelectedItemAt:(NSIndexPath * _Nonnull)indexPath;
@end


@interface ENCollectionViewPresenter (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionReusableView * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView viewForSupplementaryElementOfKind:(NSString * _Nonnull)kind atIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout referenceSizeForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout referenceSizeForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC11KeyboardSDK13ENContentView")
@interface ENContentView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)bottomKeyboardHandler;
@end


@interface ENContentView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface ENContentView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDelegate>
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface ENContentView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11KeyboardSDK17ENContentViewCell")
@interface ENContentViewCell : UICollectionViewCell
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class UIButton;
@class NSLayoutConstraint;
@class NSBundle;

SWIFT_CLASS("_TtC11KeyboardSDK21ENGuideViewController")
@interface ENGuideViewController : UIViewController <UIScrollViewDelegate>
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnBack;
@property (nonatomic, weak) IBOutlet UIScrollView * _Null_unspecified guideScrollView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewGuideFirst;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified constraintGuideFirstWidth;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewGuildeSecond;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified constraintGuideSecondWidth;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewGuideThird;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified constraintGuideThirdWidth;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified btnConfirm;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)btnConfirmHandler;
- (void)btnCloseHandler;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ENGuideViewController (SWIFT_EXTENSION(KeyboardSDK))
/// 스크롤 이벤트가 끝났을 때
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end


/// UIInputViewController 상속.  Client에서 해당 클래스를 상속받아 Keyboard Extension을 구현할 수 있도록 한다.
SWIFT_CLASS("_TtC11KeyboardSDK21ENInputViewController")
@interface ENInputViewController : UIInputViewController
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// 커스텀 영역
/// <ul>
///   <li>
///     키보드 위 툴바 부분을 세팅함.
///   </li>
///   <li>
///     여기에 사용 되는 기본적인 뷰는 wrapper 인 UIView
///   </li>
///   <li>
///     그 안에 기본적으로 사용되는 툴바인 ScrollView
///   </li>
///   <li>
///     광고나,, 붙여넣기 뷰는 Constraint 로 보여줬다 가렸다가 함.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC11KeyboardSDK24ENKeyboardCustomAreaView")
@interface ENKeyboardCustomAreaView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/// 툴바 버튼 바깥 영역 터치 핸들러
- (void)buttonTouchUpOutSide:(UIButton * _Nonnull)sender;
/// 툴바 터치 다운 핸들러
- (void)buttonTouchDown:(UIButton * _Nonnull)sender;
/// 툴바 터치 업 핸들러
- (void)buttonTouchUpInSide:(UIButton * _Nonnull)sender;
@end

@class WKUserContentController;
@class WKScriptMessage;

SWIFT_CLASS("_TtC11KeyboardSDK31ENKeyboardInquiryViewController")
@interface ENKeyboardInquiryViewController : UIViewController <UIScrollViewDelegate, WKNavigationDelegate, WKScriptMessageHandler, WKUIDelegate>
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewWebViewFrame;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewWillLayoutSubviews;
- (void)viewDidLayoutSubviews;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (IBAction)btnCloseHandler:(UIButton * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class WKWebView;
@class WKWebViewConfiguration;
@class WKNavigationAction;
@class WKWindowFeatures;
@class WKNavigation;
@class WKFrameInfo;

@interface ENKeyboardInquiryViewController (SWIFT_EXTENSION(KeyboardSDK))
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
@end


SWIFT_CLASS("_TtC11KeyboardSDK18ENKeyboardMoreView")
@interface ENKeyboardMoreView : UIView <UIGestureRecognizerDelegate, UIScrollViewDelegate, WKNavigationDelegate, WKUIDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)btnCloseHandler:(UIButton * _Nonnull)sender;
- (void)layoutSubviews;
@end


@interface ENKeyboardMoreView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDelegate>
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface ENKeyboardMoreView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface ENKeyboardMoreView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end

@class UIGestureRecognizer;

@interface ENKeyboardMoreView (SWIFT_EXTENSION(KeyboardSDK))
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end

@class UIImageView;
@class UITapGestureRecognizer;

SWIFT_CLASS("_TtC11KeyboardSDK29ENKeyboardSoundViewController")
@interface ENKeyboardSoundViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewOpacity;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewContent;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewDefaultSound;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgDefaultSoundCheck;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewSecondSound;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgSecondSoundCheck;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewThirdSound;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgThirdSoundCheck;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewFourSound;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgFourSoundCheck;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (IBAction)btnConfirmHandler:(UIButton * _Nonnull)sender;
- (IBAction)btnCancelHandler:(UIButton * _Nonnull)sender;
- (void)tapHandler:(UITapGestureRecognizer * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UILabel;

SWIFT_CLASS("_TtC11KeyboardSDK28ENKeyboardTypeViewController")
@interface ENKeyboardTypeViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewHeader;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewSelect;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewQwerty;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgQwerty;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblQwerty;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgQwertyCheck;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewTenKey;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgTenKey;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblTenKey;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imgTenKeyCheck;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewSample;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified constraintHeightViewSample;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (IBAction)btnBackHandler:(UIButton * _Nonnull)sender;
- (void)viewSelectGestureHandler:(UITapGestureRecognizer * _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class UISlider;
@class UISwitch;

SWIFT_CLASS("_TtC11KeyboardSDK20ENMainViewController")
@interface ENMainViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewHeader;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewKeyboardType;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblKeyboardType;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewKeyboardTheme;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewKeyboardHeight;
@property (nonatomic, weak) IBOutlet UISlider * _Null_unspecified sliderHeight;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewKeyboardSound;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblKeyboardSound;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewKeyboardVibrator;
@property (nonatomic, weak) IBOutlet UISwitch * _Null_unspecified switchKeyboardVibrator;
@property (nonatomic, weak) IBOutlet UISlider * _Null_unspecified sliderKeyboardVibrator;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewPreview;
@property (nonatomic, weak) IBOutlet UISwitch * _Null_unspecified switchPreview;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewKeyboardSetting;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewSample;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified constraintHeightViewSample;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (IBAction)btnBackHandler:(id _Nonnull)sender;
- (IBAction)sliderChangeHandler:(UISlider * _Nonnull)sender;
- (IBAction)switchKeyboardVibratorHandler:(UISwitch * _Nonnull)sender;
- (IBAction)sliderKeyboardVibaratorHandler:(UISlider * _Nonnull)sender;
- (IBAction)switchPreviewChangeHandler:(UISwitch * _Nonnull)sender;
- (void)viewMoveGesture:(UITapGestureRecognizer * _Nonnull)sender;
- (void)otherViewTap;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS("_TtC11KeyboardSDK14ENMoreViewCell")
@interface ENMoreViewCell : UICollectionViewCell
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11KeyboardSDK31ENNewThemeManagerViewController")
@interface ENNewThemeManagerViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified displayTitleLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified keyboardSampleView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified keyboardSampleViewHeight;
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified collectionView;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ENNewThemeManagerViewController (SWIFT_EXTENSION(KeyboardSDK))
- (IBAction)backButtonClicked:(id _Nonnull)sender;
/// 선택된 테마 미리보기 뷰의 적용버튼 동작
/// \param sender 버튼
///
- (IBAction)confirmThemeButtonClicked:(id _Nonnull)sender;
/// 선택된 테마 미리보기 뷰의 취소 버튼 동작
/// \param sender 버튼
///
- (IBAction)cancelThemeButtonClicked:(id _Nonnull)sender;
@end





/// 최 상단 공지 뷰
/// <ul>
///   <li>
///     이 부분은 툴바 상단 부분에 보여지는 뷰
///   </li>
/// </ul>
SWIFT_CLASS("_TtC11KeyboardSDK12ENNotifyView")
@interface ENNotifyView : UIView <UIGestureRecognizerDelegate, UIScrollViewDelegate, WKNavigationDelegate, WKUIDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)updateNewsTitle;
- (void)btnNewshandler:(UIButton * _Nonnull)sender;
- (void)layoutSubviews;
- (void)btnCloseHandler:(UIButton * _Nonnull)sender;
@end


@interface ENNotifyView (SWIFT_EXTENSION(KeyboardSDK))
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11KeyboardSDK22ENPPZWebViewController")
@interface ENPPZWebViewController : UIViewController <UIScrollViewDelegate, WKNavigationDelegate, WKUIDelegate>
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified viewFrame;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified constraintBridgeHeight;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified tempView;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (IBAction)btnBridgeHeaderBack:(id _Nonnull)sender;
- (IBAction)btnBridgeHeaderClose:(id _Nonnull)sender;
- (IBAction)btnMainClose:(id _Nonnull)sender;
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webViewWebContentProcessDidTerminate:(WKWebView * _Nonnull)webView;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class ENTapGesture;

SWIFT_CLASS("_TtC11KeyboardSDK18ENPointContentView")
@interface ENPointContentView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)bottomKeyboardHandler;
- (void)tapHandller:(ENTapGesture * _Nonnull)sender;
@end


SWIFT_CLASS("_TtC11KeyboardSDK15ENTabButtonView")
@interface ENTabButtonView : UIView
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified displayLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified iconImageView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11KeyboardSDK21ENTabContentPresenter")
@interface ENTabContentPresenter : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum ENThemeSelectedTab : NSInteger;

SWIFT_CLASS("_TtC11KeyboardSDK14ENTabPresenter")
@interface ENTabPresenter : NSObject
@property (nonatomic) enum ENThemeSelectedTab selectedTab;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ENTabPresenter (SWIFT_EXTENSION(KeyboardSDK))
- (void)tapGestureExcuteWithTap:(UITapGestureRecognizer * _Nonnull)tap;
@end


SWIFT_CLASS("_TtC11KeyboardSDK12ENTapGesture")
@interface ENTapGesture : UITapGestureRecognizer
- (nonnull instancetype)initWithTarget:(id _Nullable)target action:(SEL _Nullable)action OBJC_DESIGNATED_INITIALIZER;
@end

@class DHPaddedLabel;

SWIFT_CLASS("_TtC11KeyboardSDK33ENThemeCategoryCollectionViewCell")
@interface ENThemeCategoryCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet DHPaddedLabel * _Null_unspecified labelName;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified selecteIndicatorView;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11KeyboardSDK25ENThemeCategoryHeaderView")
@interface ENThemeCategoryHeaderView : GSKStretchyHeaderView
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified textCategoryCollectionView;
@property (nonatomic, strong) IBOutlet NSLayoutConstraint * _Null_unspecified constraintTextCategoryTopMargin;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@interface ENThemeCategoryHeaderView (SWIFT_EXTENSION(KeyboardSDK)) <GSKStretchyHeaderViewStretchDelegate>
- (void)stretchyHeaderView:(GSKStretchyHeaderView * _Nonnull)headerView didChangeStretchFactor:(CGFloat)stretchFactor;
@end


@interface ENThemeCategoryHeaderView (SWIFT_EXTENSION(KeyboardSDK)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC11KeyboardSDK24ENThemeCategoryPresenter")
@interface ENThemeCategoryPresenter : ENCollectionViewPresenter
- (void)updateCellDataFor:(UICollectionViewCell * _Nullable)cell indexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)loadData;
@end



@interface ENThemeCategoryPresenter (SWIFT_EXTENSION(KeyboardSDK))
- (NSInteger)numberOfItemsWithSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)sizeForHeaderWithSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)didSelectedItemAt:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC11KeyboardSDK25ENThemeCollectionViewCell")
@interface ENThemeCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified rootView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified shadowView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified selectionView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageViewThumbnail;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageViewSelectIcon;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified labelName;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified badgeImageView;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ENThemeSelectedTab, closed) {
  ENThemeSelectedTabUnknown = 0,
  ENThemeSelectedTabCategory = 1001,
};


SWIFT_CLASS("_TtC11KeyboardSDK20ENThemeViewPresenter")
@interface ENThemeViewPresenter : ENTabContentPresenter
@end










@class NSURL;

@interface UIViewController (SWIFT_EXTENSION(KeyboardSDK))
- (BOOL)openURL:(NSURL * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11KeyboardSDK7URLUtil")
@interface URLUtil : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
